fr:
  lang: "/fr"
  langUrl: "r30/lp-f/"
  langResearchesTitle: "Recherches de publications"
  langPath: "fr"
  langReadingSentence: "La lecture pour cette semaine est"
  langPortionSentence: "La portion pour aujourd'hui va de"
  langPortionTo: "à"
  langPortionHeader: "Portion du jour"
  langPortionFooter: "Connexion compte personnel"
  langChapter: "Chapitre"
  language: "français"
  langResearchLink: "Lien"

en:
  lang: "/en"
  langUrl: "r1/lp-e/"
  langResearchesTitle: "Publications researches"
  langPath: "en"
  langReadingSentence: "This week's reading is"
  langPortionSentence: "Today's portion goes from"
  langPortionTo: "to"
  langPortionHeader: "Daily portion"
  langPortionFooter: "Link to my account"
  langChapter: "Chapter"
  language: "anglais"
  langResearchLink: "Link"

ro:
  lang: "/ro"
  langUrl: "r34/lp-m/"
  langResearchesTitle: "Cercetari de publicaţii"
  langPath: "ro"
  langReadingSentence: "Citirea pentru această săptămână"
  langPortionSentence: "Partea care este de citit pentru astăzi este de la"
  langPortionTo: "la"
  langPortionHeader: "Porțiune a zilei"
  langPortionFooter: "Intra in cont personal"
  langChapter: "Capitol"
  language: "roumain"
  langResearchLink: "Legătură"

it:    
  lang: "/it"
  langUrl: "r6/lp-i/"
  langResearchesTitle: "Ricerche di pubblicazioni"
  langPath: "it"
  langReadingSentence: "La lettura per questa settimana è"
  langPortionSentence: "La porzione per oggi va di"
  langPortionTo: "a"
  langPortionHeader: "Porzione del giorno"
  langPortionFooter: "Accesso al conto personale"
  langChapter: "Capitolo"
  language: "italien"
  langResearchLink: "Link"

es:    
  lang: "/es"
  langUrl: "r4/lp-s/"
  langResearchesTitle: "Búsquedas de publicaciones"
  langPath: "es"
  langReadingSentence: "La lectura para esta semana es"
  langPortionSentence: "La porción para hoy va de"
  langPortionTo: "hasta"
  langPortionHeader: "Porción de día"
  langPortionFooter: "Conexión al espacio personal"
  langChapter: "Capítulo"
  language: "espagnol"
  langResearchLink: "Link"

de:
  lang: "/de"
  langUrl: "r10/lp-x/"
  langResearchesTitle: "Publikationen Recherche"
  langPath: "de"
  langReadingSentence: "Der Leseteil für diese Woche ist"
  langPortionSentence: "Der heutige Leseteil geht von"
  langPortionTo: "bis"
  langPortionHeader: "Täglicher Leseteil"
  langPortionFooter: "Link zu meinem Account"
  langChapter: "Kapitel"
  language: "allemand"
  langResearchLink: "Link"
  
pt:
  lang: "/pt"
  langUrl: "r5/lp-t/"
  langResearchesTitle: "Pesquisa publicações"
  langPath: "pt"
  langReadingSentence: "Leitura para esta semana"
  langPortionSentence: "A porção de hoje é de"
  langPortionTo: "para"
  langPortionHeader: "Parte do dia"
  langPortionFooter: "Ligar à conta pessoal"
  langChapter: "Capítulo"
  language: "portugais"
  langResearchLink: "Link"